export const GET_SEATS = 'GET_SEATS';
export const SELECT_PERIOD = 'SELECT_PERIOD';
export const SELECT_TERRAIN = 'SELECT_TERRAIN';
export const SAVE_PERIODS_AND_TERRAINS = 'SAVE_PERIODS_AND_TERRAINS';
export const GET_TREES_BY_PERIOD_AND_TERRAIN = 'GET_TREES_BY_PERIOD_AND_TERRAIN';
export const GET_TREES_BY_PLANTID = 'GET_TREES_BY_PLANTID';
export const GET_TERRAINS_BY_PERIOD = 'GET_TERRAINS_BY_PERIOD';